name: Delete untagged images

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["bess_build", "bess-upf"]
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@9dee3adb4e4082ef06710f3d8aa9f7e73f89d189
        with:
          # NOTE: at now only orgs is supported
          owner: omec-project
          name: ${{ matrix.package }}
          # NOTE: using Personal Access Token
          token: ${{ secrets.CR_PAT }}
          untagged-keep-latest: 1
